"""Adiciona campo mesa_portatil

Revision ID: 9d880c04ddb8
Revises: 0691ceebcccc
Create Date: 2025-10-07 12:02:55.482432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d880c04ddb8'
down_revision = '0691ceebcccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mesa_portatil', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.drop_column('mesa_portatil')

    # ### end Alembic commands ###
