"""Expandindo modelo Agendamento com novos campos

Revision ID: aad28c4412e4
Revises: e52ed231f928
Create Date: 2025-09-26 14:38:24.107867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad28c4412e4'
down_revision = 'e52ed231f928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=140), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=False),
    sa.Column('local', sa.String(length=140), nullable=True),
    sa.Column('responsavel', sa.String(length=140), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('uso_telao', sa.Boolean(), nullable=True),
    sa.Column('gravacao', sa.Boolean(), nullable=True),
    sa.Column('uso_som', sa.Boolean(), nullable=True),
    sa.Column('transmissao', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agendamento_data_inicio'), ['data_inicio'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agendamento_data_inicio'))

    op.drop_table('agendamento')
    # ### end Alembic commands ###
